options:
    base: &base
        dotfileDirectory: test-dotfiles
    
    vimDirectory:
        <<: *base
        directoryName: vim
        links:
            - vimrc: .vimrc

    binDirectory:
        <<: *base
        directoryName: bin
        links:
            - bin: .scripts

    zshDirectory:
        <<: *base
        directoryName: zsh
        links:
            - zshrc: .zshrc
            - zsh-theme: .oh-my-zsh/themes/clair.zsh-theme
