options:
    base: &base
        dotfileDirectory: test-dotfiles

    vimDirectory: 
        <<: *base
        directoryName: vim
        links:
            - vimrc: .vimrc

    binDirectory:
        <<: *base
        directoryName: bin
        links:
            - bin: .scripts

    zshDirectory:
        <<: *base
        directoryName: zsh
        links:
            - zshrc: .zshrc
            - zsh-theme: .oh-my-zsh/themes/clair.zsh-theme

    discordDirectory:
        <<: *base
        directoryName: discord
        links: 
            - discordtheme: DiscordThemes/NordenLights.css

    comptonDirectory:
        <<: *base
        directoryName: compton
        links:
            - compton.conf: .config/compton.conf

    dunstDirectory:
        <<: *base
        directoryName: dunst
        links:
            - dunstrc: .config/dunst/dunstrc

    mpdDirectory:
        <<: *base
        directoryName: mpd
        links:
            - conf: .mpd/mpd.conf

    ncmpcppDirectory:
        <<: *base
        directoryName: ncmpcpp
        links:
            - config: .ncmpcpp/config

    obthemesDirectory:
        <<: *base
        directoryName: obthemes
        links:
            - themes: .themes

    openboxDirectory:
        <<: *base
        directoryName: openbox
        links:
            - menu: .config/openbox/menu.xml
            - rc: .config/openbox/rc.xml
            - autostart: .config/openbox/autostart

    urxvtDirectory:
        <<: *base
        directoryName: urxvt
        links:
            - xresources: .Xresources

    wallpaperDirectory:
        <<: *base
        directoryName: wallpaper
        links:
            - wallpaper: Wallpapers


