options:
    base: &base
        dotfileDirectory: test-dotfiles2

    vimPackage: 
        <<: *base
        directoryName: vim
        links:
            - vimrc: .vimrc

    binPackage:
        <<: *base
        directoryName: bin
        links:
            - bin: .scripts

    zshPackage:
        <<: *base
        directoryName: zsh
        links:
            - zshrc: .zshrc
            - zsh-theme: .oh-my-zsh/themes/clair.zsh-theme

    discordPackage:
        <<: *base
        directoryName: discord
        links: 
            - discordtheme: DiscordThemes/NordenLights.css

    comptonPackage:
        <<: *base
        directoryName: compton
        links:
            - compton.conf: .config/compton.conf

    dunstPackage:
        <<: *base
        directoryName: dunst
        links:
            - dunstrc: .config/dunst/dunstrc

    mpdPackage:
        <<: *base
        directoryName: mpd
        links:
            - conf: .mpd/mpd.conf

    ncmpcppPackage:
        <<: *base
        directoryName: ncmpcpp
        links:
            - config: .ncmpcpp/config

    obthemesPackage:
        <<: *base
        directoryName: obthemes
        links:
            - themes: .themes

    openboxPackage:
        <<: *base
        directoryName: openbox
        links:
            - menu: .config/openbox/menu.xml
            - rc: .config/openbox/rc.xml
            - autostart: .config/openbox/autostart

    urxvtPackage:
        <<: *base
        directoryName: urxvt
        links:
            - xresources: .Xresources

    wallpaperPackage:
        <<: *base
        directoryName: wallpaper
        links:
            - wallpaper: Wallpapers


